### ISSUE TITLE
IllegalStateException on 5.16.0

### ISSUE THREAD

**Issue by casolorz** [mopub/mopub-android-sdk#458]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Device model and OS Version:Galaxy J7 Android 7

I just upgraded my app from `5.10.0` to `5.16.0` and last night I released my first beta. Even though I had no problem with ads during my own testing, this morning I already had 1 crash. No idea how common this crash is going to be, or how it happened, or how to reproduce it. I only have the information Crashlytics gives me.  Only think I know is this is the first time I've seen this crash. 

This is the stack trace:

```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4658)
       at android.view.ViewGroup.addView(ViewGroup.java:4499)
       at android.view.ViewGroup.addView(ViewGroup.java:4439)
       at android.view.ViewGroup.addView(ViewGroup.java:4412)
       at com.mopub.mobileads.FullscreenAdController.onVideoFinish(FullscreenAdController.java:377)
       at com.mopub.mobileads.VastVideoViewController$PlayerCallback.onPlaybackCompleted(VastVideoViewController.java:666)
       at androidx.media2.player.MediaPlayer$Mp2Callback$6.callCallback(MediaPlayer.java:3434)
       at androidx.media2.player.MediaPlayer$33.run(MediaPlayer.java:2969)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by datada** [comment]
Same issue, many crashes occur
![image](https://user-images.githubusercontent.com/4970418/111094513-08795c00-856e-11eb-8738-cd0b59a543cc.png)

**Comment by casolorz** [comment]
Considering I only have it in beta and only for a few days, a ton of users are having the issue. I never have that many crashes for a single issue on a beta version.

**Comment by p158276** [comment]
Hi @casolorz @datada ,
Thanks for bringing that to our attention. We are aware of the issue and investigating internally. Can you help with the reproducible step? Besides, is the crash only happened in specific OS version or devices? 

Yoyo Lin 
MoPub Team

**Comment by casolorz** [comment]
Unfortunately I have no idea how to reproduce, but I released my beta again with 5.15.0 and it hasn't had a single crash on crashlytics related to this.

**Comment by datada** [comment]
This issue can occur on any device. I have no idea how to reproduce.
I used Mopub mediation and added Unity ads and iron Source as networks.
I guess the problem is related to Unity ads or iron Source with fullscreen ads

**Comment by casolorz** [comment]
I actually don't use unity or iron source. I use mopub, fb, admob full screen ads.

**Comment by p158276** [comment]
Thanks for providing all this valuable information! We will address the fix in the next SDK release. Stay tuned.

**Comment by Saren-Arterius** [comment]
I see 5.16.2 attempts to fix this issue, but 
`
        // remove mImageView first to prevent IllegalStateException when added to relativeLayout
        final ViewGroup imageViewParent = (ViewGroup) mImageView.getParent();
        if (imageViewParent != null) {
            imageViewParent.removeView(mImageView);
        }
`
mImageView can be null, which causes npe and crashes the app.

**Comment by chauduyphanvu** [comment]
@Saren-Arterius, are you seeing any new crashes with that?

**Comment by wacamoe** [comment]
@Saren-Arterius you are absolutely correct - we will patch this ASAP.

**Comment by wacamoe** [comment]
@Saren-Arterius we actually hotpatched 5.16.2 itself to address this since we've only been live < 24 hours. This is now addressed in 5.16.2 itself.

**Comment by sametbars** [comment]
I noticed that I started to get this crash reports after I added networks on Mopub Network tab and enabled advanced biddings in my ad units. (I paused the networks immediately after adding because I did not updated the app to have required adapters.) I haven't had have this error before that.

Then, after seeing the huge amount of crash reports, I deleted all networks and disabled advanced bidding. But they are still coming.

**Comment by chauduyphanvu** [comment]
@sametbars, please invalidate your Android Studio project via File -> "Invalidates caches / restart" to get the latest fix we've deployed. Let us know if that resolves the issue!

**Comment by casolorz** [comment]
I invalidated, plus deleted the cache directory on my home directory for gradle and I still get this when looking at the code inside Android Studio:

```
   final ViewGroup imageViewParent = (ViewGroup) mImageView.getParent();
        if (imageViewParent != null) {
            imageViewParent.removeView(mImageView);
        }
```

**Comment by chauduyphanvu** [comment]
@casolorz, thanks for the note. Please see the discussion on https://github.com/mopub/mopub-android-sdk/issues/460 for ongoing updates on this issue.

Since the original issue on this thread has been resolved, I will close it now. You may continue to follow along on the other issue thread.
